name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: go build ./cmd/inventory
      - name: Docker Build
        run: docker build -t inventory .
      - name: Start PostgreSQL
        run: docker run -d --name postgres -e POSTGRES_PASSWORD=password -p 5433:5432 postgres:17
      - name: Run Tests
        run: go test ./... -v